### PR TITLE
Add license title

### PR DESCRIPTION
**Pull request by waldyrious**
It's not strictly required, but it's useful metadata, and part of the recommended license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license)

### CODE REVIEW

**Comment by fragglet** [comment]
Thanks!

**Comment by waldyrious** [comment]
@fragglet mind if I send similar PRs to your other repos? :)

**Comment by fragglet** [comment]
Please do!

**Comment by waldyrious** [comment]
@fragglet cool, I'll get to it shortly ;)

**Pull request merged**
