### PR TITLE
fix issues in list.[ch]

### PR DESCRIPTION
**Pull request by hexingb**
add some validation check of input parameters.
add a callback function to clean up ListValue when remove entries.

### CODE REVIEW

**Comment by fragglet** [comment]
Please fix failing test.

    test-cpp.cpp:167:16: error: too few arguments to function ‘void list_free(ListEntry*, ListFreeFunc)’

**Comment by fragglet** [comment]
Looks okay in theory; can you please rewrite your commits to separate them into logically separate changes? ie. not just one commit named "fix issues"; one to add input validation, another to add the callback function. Please include meaningful descriptions; see here for suggestions:

http://chris.beams.io/posts/git-commit/#seven-rules

**Comment by hexingb** [comment]
Sorry for this. git is not much familiar to me. I'll rewrite these again.
BTW, what do you mean "remove this"? remove what?

**Comment by fragglet** [comment]
No problem, I understand.

"Remove this" was a reference to the terminating NULL in list_to_array(). This isn't necessary and I'd rather not add it.

**Comment by hexingb** [comment]
OK. I'll rewrite these again. Thank you for your patience.

**Pull request closed without merging**
